version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Gradle...
      - chmod +x gradlew  # gradlew 실행 권한 부여
      - ./gradlew dependencies

  build:
    commands:
      - echo Building the application...
      - ./gradlew build -x test

artifacts:
  files:
    - build/libs/*.jar
